ARG IMAGE=opensuse/leap:15
ARG DEPS_SH=install-openvpn-build-deps-opensuse-leap.sh
ARG MY_NAME="buildbot-worker-opensuse-leap-15"
ARG MY_VERSION="v1.0.3"
ARG ASIO_REF="asio-1-18-2"
ARG INSTALL_GDBUSPP="no"
