FROM $IMAGE
LABEL maintainer="OpenVPN Community Project"
USER root
WORKDIR /buildbot

# Install build dependencies for OpenVPN
RUN mkdir -p /buildbot
ARG DEPS_SH
COPY scripts/${DEPS_SH} /buildbot/
RUN set -ex; \
    /buildbot/${DEPS_SH}; \
    rm -f ${DEPS_SH}

# Install buildbot
ARG MY_NAME
COPY scripts/install-buildbot.sh t_client/*.crt t_client/*.rc ${MY_NAME}/t_client.* /buildbot/
RUN set -ex; \
    /buildbot/install-buildbot.sh; \
    rm -f /buildbot/install-buildbot.sh

COPY buildbot.tac /buildbot/
RUN mkdir -p /home/buildbot

CMD ["twistd", "--pidfile=", "--nodaemon", "--python=buildbot.tac"]

