FROM $IMAGE
LABEL maintainer="OpenVPN Community Project"
USER root
WORKDIR /buildbot

# Install build dependencies for OpenVPN
RUN mkdir -p /buildbot
ARG DEPS_SH
COPY scripts/${DEPS_SH} /buildbot/
RUN set -ex; \
    /buildbot/${DEPS_SH}; \
    rm -f ${DEPS_SH}

# Install gdbuspp, which is a dependency of openvpn3-linux
ARG INSTALL_GDBUSPP
COPY scripts/install-gdbuspp.sh /buildbot/
RUN set -x; \
    /buildbot/install-gdbuspp.sh; \
    rm -f install-gdbuspp.sh; \
    rm -rf /buildbot/gdbuspp

# Install buildbot
ARG MY_NAME
ARG PIP_INSTALL_OPTS
COPY scripts/install-buildbot.sh t_client/*.crt t_client/*.rc t_client/*.txt ${MY_NAME}/t_client.* ${MY_NAME}/t_server_null.rc /buildbot/
RUN set -ex; \
    /buildbot/install-buildbot.sh; \
    rm -f /buildbot/install-buildbot.sh

COPY buildbot.tac /buildbot/
RUN mkdir -p /home/buildbot

CMD ["twistd", "--pidfile=", "--nodaemon", "--python=buildbot.tac"]
