ARG IMAGE=ubuntu:23.04
ARG DEPS_SH=install-openvpn-build-deps-ubuntu.sh
ARG MY_NAME="buildbot-worker-ubuntu-2304"
ARG PIP_INSTALL_OPTS="--break-system-packages"
ARG MY_VERSION="v1.0.0"
ARG ASIO_REF="asio-1-18-2"
