ARG IMAGE=debian:12
ARG DEPS_SH=install-openvpn-build-deps-ubuntu.sh
ARG MY_NAME="buildbot-worker-debian-12"
ARG PIP_INSTALL_OPTS="--break-system-packages"
ARG MY_VERSION="v1.1.0"
ARG ASIO_REF="asio-1-18-2"
ARG INSTALL_GDBUSPP="yes"
